// Original illustrative motion studies. The linked sources establish movement
// families and posture names, not measured angles or validated muscle behaviour.
import { armsDown, seated } from './additional-studies.mjs';

const staff = { ...armsDown, 'hip-left': [-90, 0, 0], 'hip-right': [-90, 0, 0] };
const supine = { ...armsDown, root: [-90, 0, 0] };
const bentSupine = { ...supine, 'hip-left': [-55, 0, 0], 'hip-right': [-55, 0, 0], 'femur-left': [110, 0, 0], 'femur-right': [110, 0, 0] };
const prone = { ...armsDown, root: [90, 0, 0] };
const sideLying = { ...bentSupine, root: [-90, 0, 90] };
const kneeling = { ...armsDown, 'femur-left': [135, 0, 0], 'femur-right': [135, 0, 0] };
const overhead = { 'scapula-left': [0, 0, -80], 'scapula-right': [0, 0, 80] };
const forwardArms = { 'scapula-left': [0, 85, 90], 'scapula-right': [0, -85, -90] };
const bentArms = { ...forwardArms, 'humerus-left': [0, 70, 0], 'humerus-right': [0, -70, 0] };
// Orient the thigh's hinge plane from two pelvis-space segment directions.
// Knee flexion stays on its X hinge; outward thigh rotation, rather than a
// sideways knee rotation, brings the shin across the seated support plane.
const unit = vector => vector.map(value => value / Math.hypot(...vector));
const dot = (a, b) => a.reduce((sum, value, index) => sum + value * b[index], 0);
function foldedLeg(side, thigh, shin) {
  const down = unit(thigh), next = unit(shin), cosine = dot(down, next);
  const y = down.map(value => -value);
  const z = unit(next.map((value, axis) => cosine * down[axis] - value));
  const x = [y[1] * z[2] - y[2] * z[1], y[2] * z[0] - y[0] * z[2], y[0] * z[1] - y[1] * z[0]];
  const degrees = 180 / Math.PI;
  return {
    [`hip-${side}`]: [Math.atan2(y[2], z[2]), Math.asin(Math.max(-1, Math.min(1, -x[2]))), Math.atan2(x[1], x[0])].map(value => value * degrees),
    [`femur-${side}`]: [Math.acos(Math.max(-1, Math.min(1, cosine))) * degrees, 0, 0],
    [`tibia-${side}`]: [90, 0, 0]
  };
}
const crossedSeat = (depth = 1, lift = 0) => ({
  ...foldedLeg('left', [-1, 0, .85], [1, lift, .15 - depth * .18]),
  ...foldedLeg('right', [1, 0, .85], [-1, lift, .28 - depth * .15])
});
const boundSeat = spread => ({
  ...foldedLeg('left', [-spread, 0, .6], [1, 0, .35]),
  ...foldedLeg('right', [spread, 0, .6], [-1, 0, .35])
});
const placements = { Seated: {}, Standing: {}, 'Long sitting': { root: [0, -750, 0] }, Supine: { root: [0, 160, 900] }, Prone: { root: [0, 180, -900] }, 'Side lying': { root: [0, 240, 900] }, Kneeling: { root: [0, -410, 0] }, Inverted: { root: [0, 1850, 0] } };
const bases = { Seated: seated, Standing: armsDown, 'Long sitting': staff, Supine: bentSupine, Prone: prone, 'Side lying': sideLying, Kneeling: kneeling, Inverted: { ...armsDown, root: [0, 0, 180] } };
export const REGIONS = { head: 'Head and neck', shoulders: 'Shoulders and arms', spine: 'Spine and ribs', hips: 'Pelvis and hips', legs: 'Legs and feet', whole: 'Whole-body coordination' };
const studies = [];

// Pose fields are local Euler degrees on the existing shared rig. Each listed
// waypoint is an intentional coordination change; neither timing nor side
// variants are counted as additional collection entries.
function study(tradition, id, label, region, position, summary, poses, options = {}) {
  const base = options.base || bases[position];
  studies.push({ tradition, id: `${id}-study`, label, region, position, summary, poses, base,
    placement: options.placement || placements[position], group: options.group || (tradition === 'feldenkrais' ? REGIONS[region] : position), ...options });
}
const f = (...args) => study('feldenkrais', ...args);
const y = (...args) => study('yoga', ...args);
const a = (...args) => study('alexander', ...args);

f('head-turn', 'Head turning', 'head', 'Seated', 'The head turns relative to the upper neck, then passes back through centre.', [{ head: [0, 18, 0], 'neck-base': [0, 5, 0] }, { head: [0, -18, 0], 'neck-base': [0, -5, 0] }]);
f('head-chest-follow', 'Head leading the chest', 'head', 'Seated', 'A head turn begins before the upper chest follows in the same direction.', [{ head: [0, 18, 0] }, { head: [0, 10, 0], 'thoracic-upper': [0, 12, 0], 'thoracic-lower': [0, 5, 0] }]);
f('head-figure-eight', 'Small head figure eight', 'head', 'Seated', 'Combined nodding and turning traces two small loops at the skull.', [{ head: [5, 12, 3] }, { head: [-5, 12, -3] }, { head: [5, -12, -3] }, { head: [-5, -12, 3] }]);
f('neck-lengthening', 'Head and neck counterbalance', 'head', 'Seated', 'The lower neck inclines as the skull counter-rotates, changing the head-to-chest relationship.', [{ 'neck-base': [7, 0, 0], head: [-7, 0, 0] }, { 'neck-base': [-5, 0, 0], head: [5, 0, 0] }]);
f('shoulder-shrug', 'Shoulder elevation and settling', 'shoulders', 'Seated', 'Both clavicles and shoulder blades rise together before settling.', [{ 'clavicle-left': [0, 0, -8], 'clavicle-right': [0, 0, 8], 'scapula-left': [0, 0, 83], 'scapula-right': [0, 0, -83] }, { 'clavicle-left': [0, 0, 2], 'clavicle-right': [0, 0, -2] }], { translations: [{ 'scapula-left': [0, 16, 0], 'scapula-right': [0, 16, 0] }, {}] });
f('alternating-shoulder-circles', 'Alternating shoulder circles', 'shoulders', 'Seated', 'The two shoulder blades follow small offset loops around the rib cage.', [{ 'scapula-left': [0, 5, 85], 'scapula-right': [0, 5, -95] }, { 'scapula-left': [0, -5, 95], 'scapula-right': [0, -5, -85] }, { 'scapula-left': [0, 5, 95], 'scapula-right': [0, 5, -85] }]);
f('cross-body-reach', 'Cross-body reach', 'shoulders', 'Seated', 'One elevated arm approaches the opposite side while the chest follows slightly.', [{ 'scapula-left': [0, 80, 50], 'humerus-left': [0, 35, 0] }, { 'scapula-left': [0, 110, 50], 'humerus-left': [0, 55, 0], 'thoracic-upper': [0, -5, 0] }]);
f('palm-turning', 'Palm turning', 'shoulders', 'Seated', 'With the arm supported forward, the forearm and hand rotate around their long axis.', [{ 'humerus-left': [65, 20, 0] }, { 'humerus-left': [-65, 20, 0] }], { base: { ...seated, 'scapula-left': [0, 80, 90], 'humerus-left': [0, 20, 0] } });
f('wrist-deviation', 'Hand moving side to side', 'shoulders', 'Seated', 'The hand moves across the forearm line while wrist flexion stays small.', [{ 'forearm-left': [0, -16, 0] }, { 'forearm-left': [0, 18, 0] }], { base: { ...seated, 'humerus-left': [0, 80, 0] } });
f('arms-opening', 'Arms opening around the chest', 'shoulders', 'Seated', 'Two forward arms open sideways with a small accompanying chest extension.', [forwardArms, { 'scapula-left': [0, 15, 5], 'scapula-right': [0, -15, -5], 'thoracic-upper': [-4, 0, 0] }]);
f('elbow-circle', 'Elbow tracing a circle', 'shoulders', 'Seated', 'A bent arm traces a loop by combining elevation and rotation at the shoulder.', [{ 'scapula-left': [0, 60, 40], 'humerus-left': [0, 100, 0] }, { 'scapula-left': [0, 85, 65], 'humerus-left': [0, 100, 0] }, { 'scapula-left': [0, 45, 75], 'humerus-left': [0, 100, 0] }]);
f('arm-spiral', 'Arm spiral', 'shoulders', 'Seated', 'Shoulder rotation, elbow folding, and forearm turning enter successively into one arm path.', [{ 'scapula-left': [0, 35, 30] }, { 'scapula-left': [15, 55, 20], 'humerus-left': [45, 70, 0] }, { 'scapula-left': [5, 80, 45], 'humerus-left': [70, 105, 0], 'forearm-left': [10, 5, -15] }]);
f('hand-behind', 'Hand travelling behind the trunk', 'shoulders', 'Seated', 'An arm moves backward before the elbow folds, exposing shoulder and elbow contributions.', [{ 'scapula-left': [0, -25, 90] }, { 'scapula-left': [0, -35, 100], 'humerus-left': [0, 100, 0], 'thoracic-upper': [0, 4, 0] }]);
f('overhead-rib-reach', 'One arm overhead with rib response', 'shoulders', 'Seated', 'One arm rises first; a small rib-cage side bend then extends the pathway.', [{ 'scapula-left': [0, 0, -55] }, { 'scapula-left': [0, 0, -80], 'thoracic-upper': [0, 0, -6], 'lumbar-spine': [0, 0, -3] }]);
f('seated-side-arc', 'Seated side-bending arc', 'spine', 'Seated', 'The lumbar and thoracic regions incline together, then reverse their arc.', [{ 'lumbar-spine': [0, 0, 8], 'thoracic-lower': [0, 0, 6], 'neck-base': [0, 0, -4] }, { 'lumbar-spine': [0, 0, -8], 'thoracic-lower': [0, 0, -6], 'neck-base': [0, 0, 4] }]);
f('sternum-lift', 'Sternum lifting and settling', 'spine', 'Seated', 'Upper-thoracic extension changes the sternum angle while the lower trunk stays comparatively quiet.', [{ 'thoracic-upper': [-7, 0, 0], 'neck-base': [3, 0, 0] }, { 'thoracic-upper': [5, 0, 0], 'neck-base': [-2, 0, 0] }]);
f('standing-spiral', 'Standing spiral', 'whole', 'Standing', 'Pelvis, ribs, and head progressively contribute to a standing turn.', [{ pelvis: [0, 8, 0], 'hip-left': [0, -8, 0], 'hip-right': [0, -8, 0] }, { pelvis: [0, 8, 0], 'hip-left': [0, -8, 0], 'hip-right': [0, -8, 0], 'thoracic-lower': [0, 10, 0], head: [0, 12, 0] }]);
f('supine-pelvis-roll', 'Back-lying pelvic roll', 'hips', 'Supine', 'A small pelvic tilt changes the lumbar curve while bent legs counterbalance.', [{ pelvis: [6, 0, 0], 'hip-left': [-61, 0, 0], 'hip-right': [-61, 0, 0], 'lumbar-spine': [-4, 0, 0] }, { pelvis: [-6, 0, 0], 'hip-left': [-49, 0, 0], 'hip-right': [-49, 0, 0], 'lumbar-spine': [4, 0, 0] }]);
f('supine-pelvic-circle', 'Back-lying pelvic circle', 'hips', 'Supine', 'Small pelvic tilts combine into a loop, with the lumbar region responding.', [{ pelvis: [5, 0, 0], 'lumbar-spine': [-3, 0, 0] }, { pelvis: [0, 0, 5], 'lumbar-spine': [0, 0, -3] }, { pelvis: [-5, 0, 0], 'lumbar-spine': [3, 0, 0] }, { pelvis: [0, 0, -5], 'lumbar-spine': [0, 0, 3] }]);
f('alternating-knee-lift', 'Alternating bent-knee lifts', 'hips', 'Supine', 'Each bent thigh approaches the trunk in turn while the other leg keeps its starting shape.', [{ 'hip-left': [-85, 0, 0], 'femur-left': [125, 0, 0] }, { 'hip-right': [-85, 0, 0], 'femur-right': [125, 0, 0] }]);
f('knees-opening', 'Bent knees opening apart', 'hips', 'Supine', 'The two thighs open away from one another and return without extending the knees.', [{ 'hip-left': [-55, -18, -12], 'hip-right': [-55, 18, 12] }, { 'hip-left': [-55, -30, -20], 'hip-right': [-55, 30, 20] }]);
f('hip-circle', 'Bent-leg hip circle', 'hips', 'Supine', 'A bent thigh traces a small loop combining hip flexion and sideways movement.', [{ 'hip-left': [-80, -10, -8] }, { 'hip-left': [-95, 0, 0] }, { 'hip-left': [-80, 10, 8] }]);
f('knee-across', 'One knee across the midline', 'hips', 'Supine', 'One bent leg moves across the trunk as the pelvis begins a small following roll.', [{ 'hip-left': [-70, 16, 12] }, { 'hip-left': [-75, 22, 18], pelvis: [0, 8, 0], 'lumbar-spine': [0, -4, 0] }]);
f('sideways-heel-slide', 'Heel sliding sideways', 'legs', 'Supine', 'A long leg moves away from the midline with little knee movement.', [{ 'hip-left': [0, -12, -8] }, { 'hip-left': [0, -22, -16] }], { base: supine });
f('long-leg-roll', 'Long leg rolling inward and outward', 'legs', 'Supine', 'Rotation at one hip turns the knee and foot together along a long leg.', [{ 'hip-left': [0, -22, 0] }, { 'hip-left': [0, 22, 0] }], { base: supine });
f('floor-arm-sweep', 'Arm sweeping along the floor plane', 'shoulders', 'Supine', 'One arm sweeps sideways toward overhead while the trunk stays horizontal.', [{ 'scapula-left': [0, 0, 20] }, { 'scapula-left': [0, 0, -65], 'thoracic-upper': [0, 0, -3] }], { base: supine });
f('diagonal-elbow-knee', 'Diagonal elbow and knee approach', 'whole', 'Supine', 'Trunk flexion and rotation bring a bent elbow toward the opposite raised knee.', [{ 'hip-right': [-90, 0, 0], 'scapula-left': [0, 70, 30], 'humerus-left': [0, 110, 0] }, { 'hip-right': [-100, 0, 0], 'thoracic-lower': [12, -10, 0], 'thoracic-upper': [8, -8, 0], 'scapula-left': [0, 80, 30], 'humerus-left': [0, 110, 0] }]);
f('side-lying-book', 'Side-lying arm and chest opening', 'spine', 'Side lying', 'The upper arm opens first, followed by a small rotation through the chest.', [{ 'scapula-right': [0, -70, -30] }, { 'scapula-right': [0, -20, 0], 'thoracic-upper': [0, -15, 0], 'thoracic-lower': [0, -8, 0] }]);
f('side-lying-leg-arc', 'Side-lying upper-leg arc', 'hips', 'Side lying', 'The upper thigh moves forward and backward while the lower leg remains folded.', [{ 'hip-right': [-80, 0, 15], 'femur-right': [65, 0, 0] }, { 'hip-right': [-15, 0, 15], 'femur-right': [65, 0, 0] }]);
f('side-lying-head-lift', 'Side-lying head lift and return', 'head', 'Side lying', 'The head rises a small distance through lateral neck motion, then returns.', [{ 'neck-base': [0, 0, -5], head: [0, 0, -4] }, { 'neck-base': [0, 0, -9], head: [0, 0, -5] }]);
f('rolling-back-side', 'Rolling from the back toward the side', 'whole', 'Supine', 'Bent knees and trunk turn together through a partial whole-body roll.', [{ root: [-90, 0, 25] }, { root: [-90, 0, 65], 'thoracic-upper': [0, -5, 0] }]);
f('rolling-knee-led', 'Knee-led rolling', 'whole', 'Supine', 'A crossing knee starts the roll before the ribs and head follow.', [{ 'hip-left': [-75, 20, 12], pelvis: [0, 8, 0] }, { root: [-90, 0, 40], 'hip-left': [-75, 20, 12], 'thoracic-lower': [0, -5, 0], head: [0, -8, 0] }]);
f('alternating-heel-lift', 'Alternating heel lifts in sitting', 'legs', 'Seated', 'Ankle extension alternates between the feet, with small knee responses.', [{ 'tibia-left': [16, 0, 0], 'femur-left': [86, 0, 0] }, { 'tibia-right': [16, 0, 0], 'femur-right': [86, 0, 0] }]);
f('foot-knee-differentiation', 'Foot and knee counter-directions', 'legs', 'Seated', 'A small thigh turn and opposing ankle angle separate the knee direction from the foot direction.', [{ 'hip-left': [-90, 10, 0], 'tibia-left': [0, -10, 0] }, { 'hip-left': [-90, -10, 0], 'tibia-left': [0, 10, 0] }]);
f('ankle-wrist-coordination', 'Ankle and wrist coordination', 'whole', 'Seated', 'One wrist and the opposite ankle flex together and then oppose one another.', [{ 'forearm-left': [0, 0, -18], 'tibia-right': [-15, 0, 0] }, { 'forearm-left': [0, 0, -18], 'tibia-right': [15, 0, 0] }], { base: { ...seated, 'humerus-left': [0, 80, 0] } });
f('standing-weight-transfer', 'Standing side-to-side transfer', 'whole', 'Standing', 'The pelvis shifts laterally while the trunk inclines in the opposite direction.', [{ pelvis: [0, 0, 4], 'lumbar-spine': [0, 0, -4], 'hip-left': [0, 0, -4], 'hip-right': [0, 0, -4] }, { pelvis: [0, 0, -4], 'lumbar-spine': [0, 0, 4], 'hip-left': [0, 0, 4], 'hip-right': [0, 0, 4] }], { translations: [{ root: [-22, 0, 0] }, { root: [22, 0, 0] }] });
f('small-knee-bend', 'Small standing knee bend', 'legs', 'Standing', 'Both knees bend with a small hip hinge and compensating ankle motion.', [{ 'hip-left': [-10, 0, 0], 'hip-right': [-10, 0, 0], 'femur-left': [20, 0, 0], 'femur-right': [20, 0, 0] }, { 'hip-left': [-18, 0, 0], 'hip-right': [-18, 0, 0], 'femur-left': [36, 0, 0], 'femur-right': [36, 0, 0] }], { planted: true });
f('stepping-in-place', 'Alternating steps in place', 'whole', 'Standing', 'A flexed hip and knee lift each foot in turn while the opposite arm follows.', [{ 'hip-left': [-25, 0, 0], 'femur-left': [40, 0, 0], 'tibia-left': [-15, 0, 0], 'scapula-right': [0, -15, -90] }, { 'hip-right': [-25, 0, 0], 'femur-right': [40, 0, 0], 'tibia-right': [-15, 0, 0], 'scapula-left': [0, 15, 90] }]);
f('ankle-standing-sway', 'Forward and backward ankle sway', 'legs', 'Standing', 'A small whole-body inclination pivots above the ankle line without a knee bend.', [{ root: [4, 0, 0] }, { root: [-3, 0, 0] }], { planted: true });

y('revolved-triangle', 'Revolved triangle', 'spine', 'Standing', 'A split-stance hinge combines a trunk turn with opposing arm lines.', [{ pelvis: [40, 0, 0], 'hip-left': [-55, 0, 0], 'hip-right': [-25, 0, 0] }, { pelvis: [50, 0, 0], 'hip-left': [-65, 0, 0], 'hip-right': [-35, 0, 0], 'thoracic-lower': [0, 20, 0], 'thoracic-upper': [0, 15, 0], 'scapula-left': [0, 0, 0], 'scapula-right': [0, 0, 0] }], { alias: 'Parivrtta Trikonasana' });
y('revolved-side-angle', 'Revolved side angle', 'spine', 'Standing', 'A bent front leg supports a forward-inclined and rotated trunk.', [{ 'hip-left': [-45, 0, 0], 'femur-left': [70, 0, 0], 'hip-right': [20, 0, 0], 'tibia-left': [-25, 0, 0], 'tibia-right': [-20, 0, 0] }, { 'hip-left': [-45, 0, 0], 'femur-left': [70, 0, 0], 'hip-right': [20, 0, 0], 'tibia-left': [-25, 0, 0], 'tibia-right': [-20, 0, 0], 'lumbar-spine': [12, 8, 0], 'thoracic-lower': [8, 18, 0], ...bentArms }], { alias: 'Parivrtta Parsvakonasana' });
y('warrior-three', 'Warrior III', 'whole', 'Standing', 'The torso inclines as the free leg extends behind, producing opposed trunk and leg lines.', [{ pelvis: [40, 0, 0], 'hip-left': [-40, 0, 0], 'hip-right': [0, 0, 0], ...forwardArms }, { pelvis: [75, 0, 0], 'hip-left': [-75, 0, 0], 'hip-right': [10, 0, 0], ...overhead }], { alias: 'Virabhadrasana III' });
y('extended-hand-big-toe', 'Standing hand-to-big-toe arrangement', 'legs', 'Standing', 'One thigh rises and the knee opens while one arm reaches toward the raised foot.', [{ 'hip-left': [-60, 0, 0], 'femur-left': [65, 0, 0], 'scapula-left': [0, 70, 80] }, { 'hip-left': [-85, 0, 0], 'femur-left': [10, 0, 0], 'scapula-left': [0, 85, 80] }], { alias: 'Utthita Hasta Padangusthasana', note: 'Hand-to-foot contact and balance are approximate.' });
y('eagle-balance', 'Eagle balance', 'whole', 'Standing', 'A bent supporting leg and crossed free thigh combine with folded arms.', [{ 'hip-right': [-18, 0, 0], 'femur-right': [30, 0, 0], 'tibia-right': [-12, 0, 0], 'hip-left': [-30, 25, 15], 'femur-left': [70, 0, 0] }, { 'hip-right': [-22, 0, 0], 'femur-right': [36, 0, 0], 'tibia-right': [-14, 0, 0], 'hip-left': [-35, 30, 20], 'femur-left': [85, 0, 0], ...bentArms }], { alias: 'Garudasana', note: 'Leg crossing is approximate; finger and foot wrapping are not modelled.' });
y('garland-squat', 'Garland squat', 'hips', 'Standing', 'Hip and knee flexion lower the pelvis between outward-facing thighs.', [{ 'hip-left': [-50, -20, -12], 'hip-right': [-50, 20, 12], 'femur-left': [90, 0, 0], 'femur-right': [90, 0, 0] }, { 'hip-left': [-75, -25, -18], 'hip-right': [-75, 25, 18], 'femur-left': [135, 0, 0], 'femur-right': [135, 0, 0], ...bentArms }], { alias: 'Malasana', translations: [{ root: [0, -210, -80] }, { root: [0, -440, -100] }] });
y('easy-crossed-seat', 'Cross-legged seat', 'hips', 'Long sitting', 'Both hips turn outward as the knees fold into a simple crossed-leg arrangement.', [crossedSeat(.2), crossedSeat(1)], { alias: 'Swastikasana Sukhasana' });
y('accomplished-seat', 'Accomplished seat arrangement', 'hips', 'Long sitting', 'Outward-facing thighs and uneven knee folding place one heel ahead of the other.', [{ ...foldedLeg('left', [-1, 0, .5], [1, 0, -.1]), ...foldedLeg('right', [1, 0, .7], [-1, 0, -.15]) }, { ...foldedLeg('left', [-1, 0, .5], [1, 0, -.3]), ...foldedLeg('right', [1, 0, .7], [-1, 0, -.05]) }], { alias: 'Siddhasana', note: 'Heel placement is a schematic relationship, not an exact contact solution.' });
y('lotus-arrangement', 'Lotus arrangement', 'hips', 'Long sitting', 'Deeply flexed knees and externally rotated thighs illustrate the folded-leg structure.', [crossedSeat(.7, .03), crossedSeat(1.8, .18)], { alias: 'Padmasana', note: 'Foot-on-thigh contact is approximate; the rig does not model knee torsion.' });
y('hero-seat', 'Hero seat', 'legs', 'Kneeling', 'The pelvis lowers between flexed knees while the trunk stays upright.', [{ 'hip-left': [-35, 0, -5], 'hip-right': [-35, 0, 5] }, { 'hip-left': [-60, 0, -8], 'hip-right': [-60, 0, 8], 'femur-left': [150, 0, 0], 'femur-right': [150, 0, 0] }], { alias: 'Virasana', translations: [{ root: [0, -540, -50] }, { root: [0, -650, -80] }] });
y('bound-angle', 'Bound angle', 'hips', 'Long sitting', 'Both thighs open outward as the knees bend and the lower legs approach one another.', [boundSeat(.8), boundSeat(1.2)], { alias: 'Baddha Konasana', note: 'Sole-to-sole contact is approximate.' });
y('head-to-knee-fold', 'Head-to-knee fold', 'hips', 'Long sitting', 'One leg stays long as the other folds outward and the trunk inclines toward the long leg.', [{ ...foldedLeg('right', [1, 0, .7], [-1, 0, -.3]) }, { ...foldedLeg('right', [1, 0, .7], [-1, 0, -.3]), 'lumbar-spine': [18, 0, 0], 'thoracic-lower': [10, 0, 0], ...forwardArms }], { alias: 'Janu Sirsasana' });
y('marichi-fold', 'Marichi forward fold', 'hips', 'Long sitting', 'One knee rises beside the trunk while the other leg remains extended during a small forward hinge.', [{ 'hip-left': [-110, 0, -12], 'femur-left': [130, 0, 0] }, { pelvis: [18, 0, 0], 'hip-left': [-128, 0, -12], 'hip-right': [-108, 0, 0], 'femur-left': [130, 0, 0], 'lumbar-spine': [10, 0, 0] }], { alias: 'Marichyasana I', note: 'The hand bind is omitted.' });
y('half-lord-fishes', 'Half lord of the fishes', 'spine', 'Long sitting', 'A crossed bent leg accompanies rotation distributed through the seated trunk.', [{ 'hip-left': [-110, 20, 5], 'femur-left': [120, 0, 0], ...foldedLeg('right', [.6, 0, 1], [-1, 0, -.5]) }, { 'hip-left': [-110, 20, 5], 'femur-left': [120, 0, 0], ...foldedLeg('right', [.6, 0, 1], [-1, 0, -.5]), 'lumbar-spine': [0, 6, 0], 'thoracic-lower': [0, 14, 0], head: [0, 10, 0] }], { alias: 'Ardha Matsyendrasana' });
y('gate-pose', 'Gate pose', 'spine', 'Kneeling', 'One leg extends sideways as the trunk inclines and the opposite arm rises.', [{ 'hip-left': [0, 0, -55], 'femur-left': [0, 0, 0] }, { 'hip-left': [0, 0, -55], 'femur-left': [0, 0, 0], 'lumbar-spine': [0, 0, 12], 'thoracic-lower': [0, 0, 8], 'scapula-right': [0, 0, 75] }], { alias: 'Parighasana' });
y('camel-pose', 'Camel pose', 'spine', 'Kneeling', 'Extension develops through the pelvis and trunk while the knees remain folded.', [{ pelvis: [-8, 0, 0], 'hip-left': [8, 0, 0], 'hip-right': [8, 0, 0], 'lumbar-spine': [-8, 0, 0] }, { pelvis: [-12, 0, 0], 'hip-left': [12, 0, 0], 'hip-right': [12, 0, 0], 'lumbar-spine': [-12, 0, 0], 'thoracic-lower': [-12, 0, 0], 'thoracic-upper': [-8, 0, 0], 'scapula-left': [0, -20, 90], 'scapula-right': [0, 20, -90] }], { alias: 'Ustrasana' });
y('child-fold', 'Kneeling forward fold', 'hips', 'Kneeling', 'The hips fold back while the trunk inclines toward the thighs and the arms reach forward.', [{ 'hip-left': [-60, 0, 0], 'hip-right': [-60, 0, 0], pelvis: [40, 0, 0] }, { 'hip-left': [-135, 0, 0], 'hip-right': [-135, 0, 0], pelvis: [75, 0, 0], 'lumbar-spine': [10, 0, 0], ...overhead }], { alias: 'Adho Mukha Virasana Balasana Child pose', translations: [{ root: [0, -550, -350] }, { root: [0, -300, -650] }] });
y('boat-pose', 'Boat pose', 'whole', 'Long sitting', 'The torso inclines backward as both legs rise, forming an open V around the pelvis.', [{ pelvis: [-20, 0, 0], 'hip-left': [-105, 0, 0], 'hip-right': [-105, 0, 0], 'femur-left': [25, 0, 0], 'femur-right': [25, 0, 0], ...forwardArms }, { pelvis: [-35, 0, 0], 'hip-left': [-115, 0, 0], 'hip-right': [-115, 0, 0], ...forwardArms }], { alias: 'Paripurna Navasana' });
y('supine-leg-raise', 'Supine leg raise', 'legs', 'Supine', 'Both long legs rise through a middle angle and return toward the horizontal trunk.', [{ 'hip-left': [-30, 0, 0], 'hip-right': [-30, 0, 0] }, { 'hip-left': [-60, 0, 0], 'hip-right': [-60, 0, 0] }], { base: supine, alias: 'Urdhva Prasarita Padasana' });
y('reclining-hand-big-toe', 'Reclining hand-to-big-toe arrangement', 'legs', 'Supine', 'One long leg rises as the same-side arm reaches toward it, while the other leg remains extended.', [{ 'hip-left': [-55, 0, 0], 'scapula-left': [0, 70, 40] }, { 'hip-left': [-85, 0, 0], 'scapula-left': [0, 85, 30] }], { base: supine, alias: 'Supta Padangusthasana', note: 'A strap is represented by the described support, not a rendered attachment.' });
y('locust-pose', 'Locust pose', 'spine', 'Prone', 'The chest and long legs lift through small spinal and hip extensions.', [{ 'thoracic-lower': [-8, 0, 0], 'hip-left': [8, 0, 0], 'hip-right': [8, 0, 0] }, { 'thoracic-lower': [-12, 0, 0], 'thoracic-upper': [-6, 0, 0], 'hip-left': [14, 0, 0], 'hip-right': [14, 0, 0], 'scapula-left': [0, -15, 90], 'scapula-right': [0, 15, -90] }], { alias: 'Salabhasana' });
y('crocodile-rest', 'Crocodile resting arrangement', 'whole', 'Prone', 'Bent arms settle forward beside the head as the legs open slightly.', [{ ...bentArms, 'hip-left': [0, 0, -8], 'hip-right': [0, 0, 8] }, { 'scapula-left': [0, 40, -35], 'scapula-right': [0, -40, 35], 'humerus-left': [0, 115, 0], 'humerus-right': [0, -115, 0], 'hip-left': [0, 0, -12], 'hip-right': [0, 0, 12] }], { alias: 'Makarasana', note: 'This is a transition into a resting arrangement; breathing mechanics are not simulated.' });
y('bow-pose', 'Bow pose arrangement', 'whole', 'Prone', 'Knee flexion, hip extension, and a backward arm reach form the bow-shaped relationship.', [{ 'femur-left': [90, 0, 0], 'femur-right': [90, 0, 0], 'scapula-left': [0, -25, 90], 'scapula-right': [0, 25, -90] }, { 'femur-left': [115, 0, 0], 'femur-right': [115, 0, 0], 'hip-left': [16, 0, 0], 'hip-right': [16, 0, 0], 'thoracic-lower': [-12, 0, 0], 'scapula-left': [0, -40, 90], 'scapula-right': [0, 40, -90] }], { alias: 'Dhanurasana', note: 'Hand-to-ankle contact is approximate.' });
y('cobra-pose', 'Cobra pose', 'spine', 'Prone', 'The upper trunk extends from a prone base with bent arms alongside the ribs.', [{ 'thoracic-lower': [-8, 0, 0], 'humerus-left': [0, 100, 0], 'humerus-right': [0, -100, 0] }, { 'lumbar-spine': [-8, 0, 0], 'thoracic-lower': [-16, 0, 0], 'thoracic-upper': [-10, 0, 0], 'humerus-left': [0, 75, 0], 'humerus-right': [0, -75, 0] }], { alias: 'Bhujangasana' });
y('upward-facing-dog', 'Upward-facing dog', 'spine', 'Prone', 'The chest extends while the elbows lengthen, exposing the front-body arc.', [{ 'lumbar-spine': [-10, 0, 0], 'thoracic-lower': [-15, 0, 0], 'humerus-left': [0, 45, 0], 'humerus-right': [0, -45, 0] }, { 'lumbar-spine': [-14, 0, 0], 'thoracic-lower': [-20, 0, 0], 'thoracic-upper': [-12, 0, 0], 'scapula-left': [0, 35, 90], 'scapula-right': [0, -35, -90] }], { alias: 'Urdhva Mukha Svanasana', translations: [{ root: [0, 260, -900] }, { root: [0, 350, -900] }] });
y('upward-bow', 'Upward bow arrangement', 'whole', 'Supine', 'Bent knees and overhead arms accompany a segmented extension of the trunk.', [{ 'lumbar-spine': [-12, 0, 0], 'thoracic-lower': [-15, 0, 0], ...overhead }, { pelvis: [-20, 0, 0], 'lumbar-spine': [-20, 0, 0], 'thoracic-lower': [-20, 0, 0], 'thoracic-upper': [-15, 0, 0], 'hip-left': [-35, 0, 0], 'hip-right': [-35, 0, 0], ...overhead }], { alias: 'Urdhva Dhanurasana Wheel', translations: [{ root: [0, 250, 900] }, { root: [0, 360, 900] }], note: 'The arch is illustrative; hand and foot contact constraints are not solved.' });
y('reclining-hero', 'Reclining hero arrangement', 'hips', 'Supine', 'The thighs extend away from the trunk while the knees stay deeply folded.', [{ 'hip-left': [-25, 0, -6], 'hip-right': [-25, 0, 6], 'femur-left': [140, 0, 0], 'femur-right': [140, 0, 0] }, { 'hip-left': [0, 0, -8], 'hip-right': [0, 0, 8], 'femur-left': [150, 0, 0], 'femur-right': [150, 0, 0] }], { alias: 'Supta Virasana' });
y('reclining-bound-angle', 'Reclining bound angle', 'hips', 'Supine', 'Both bent thighs open away from the pelvis while the trunk rests horizontally.', [{ 'hip-left': [-40, -25, -20], 'hip-right': [-40, 25, 20], 'femur-left': [100, 0, 0], 'femur-right': [100, 0, 0] }, { 'hip-left': [-30, -45, -30], 'hip-right': [-30, 45, 30], 'femur-left': [110, 0, 0], 'femur-right': [110, 0, 0] }], { alias: 'Supta Baddha Konasana' });
y('corpse-rest', 'Savasana resting arrangement', 'whole', 'Supine', 'Long legs settle apart while the arms open slightly beside the torso.', [{ 'hip-left': [0, -8, -5], 'hip-right': [0, 8, 5], 'scapula-left': [0, 0, 80], 'scapula-right': [0, 0, -80] }, { 'hip-left': [0, -15, -8], 'hip-right': [0, 15, 8], 'scapula-left': [0, 0, 70], 'scapula-right': [0, 0, -70] }], { base: supine, alias: 'Savasana Corpse pose', note: 'The animation illustrates settling into rest, not respiration or muscle relaxation.' });
y('four-limbed-staff', 'Four-limbed staff', 'shoulders', 'Prone', 'The elbows bend beside a long trunk in a schematic low support arrangement.', [{ 'scapula-left': [0, 55, 90], 'scapula-right': [0, -55, -90], 'humerus-left': [0, 40, 0], 'humerus-right': [0, -40, 0] }, { 'scapula-left': [0, 75, 90], 'scapula-right': [0, -75, -90], 'humerus-left': [0, 90, 0], 'humerus-right': [0, -90, 0] }], { alias: 'Chaturanga Dandasana', translations: [{ root: [0, 380, -900] }, { root: [0, 250, -900] }] });
y('downward-facing-dog', 'Downward-facing dog', 'whole', 'Standing', 'The hips hinge into an inverted V as the arms align beyond the inclined trunk.', [{ pelvis: [100, 0, 0], 'hip-left': [-80, 0, 0], 'hip-right': [-80, 0, 0], ...overhead }, { pelvis: [125, 0, 0], 'hip-left': [-90, 0, 0], 'hip-right': [-90, 0, 0], ...overhead }], { alias: 'Adho Mukha Svanasana', note: 'Support contacts and balance are illustrative, not a physics simulation.' });
y('reverse-plank', 'Reverse plank', 'shoulders', 'Long sitting', 'The pelvis rises as the thighs extend and the arms reach behind the trunk.', [{ pelvis: [-25, 0, 0], 'hip-left': [-65, 0, 0], 'hip-right': [-65, 0, 0], 'scapula-left': [0, -25, 90], 'scapula-right': [0, 25, -90] }, { pelvis: [-55, 0, 0], 'hip-left': [-25, 0, 0], 'hip-right': [-25, 0, 0], 'scapula-left': [0, -55, 90], 'scapula-right': [0, 55, -90] }], { alias: 'Purvottanasana', translations: [{ root: [0, -530, 0] }, { root: [0, -260, 0] }] });
y('fish-pose', 'Fish pose arrangement', 'spine', 'Supine', 'The upper thorax extends while the legs stay long and the arms remain beside the trunk.', [{ 'thoracic-lower': [-10, 0, 0], 'thoracic-upper': [-8, 0, 0] }, { 'thoracic-lower': [-15, 0, 0], 'thoracic-upper': [-12, 0, 0], 'neck-base': [-6, 0, 0] }], { base: supine, alias: 'Matsyasana', note: 'Head support and cervical loading are not modelled.' });
y('headstand-line', 'Headstand alignment study', 'whole', 'Inverted', 'A pre-positioned inverted trunk lengthens its bent legs toward a vertical arrangement.', [{ 'hip-left': [-25, 0, 0], 'hip-right': [-25, 0, 0], 'femur-left': [50, 0, 0], 'femur-right': [50, 0, 0], ...overhead }, { 'hip-left': [0, 0, 0], 'hip-right': [0, 0, 0], ...overhead }], { alias: 'Salamba Sirsasana', note: 'Starts already inverted; mounting, head contact, loading, and balance are not represented.' });
y('shoulderstand-line', 'Shoulderstand alignment study', 'whole', 'Inverted', 'Hip flexion decreases above an inclined trunk while the arms fold toward the back.', [{ pelvis: [20, 0, 0], 'hip-left': [-35, 0, 0], 'hip-right': [-35, 0, 0], 'humerus-left': [0, 100, 0], 'humerus-right': [0, -100, 0] }, { pelvis: [15, 0, 0], 'hip-left': [-15, 0, 0], 'hip-right': [-15, 0, 0], 'thoracic-upper': [15, 0, 0], 'humerus-left': [0, 120, 0], 'humerus-right': [0, -120, 0] }], { alias: 'Salamba Sarvangasana', note: 'Already inverted schematic; neck support and loading are not modelled.' });
y('plough-arrangement', 'Plough arrangement', 'hips', 'Inverted', 'Both long legs move over the trunk through increasing hip flexion.', [{ 'hip-left': [-55, 0, 0], 'hip-right': [-55, 0, 0] }, { 'hip-left': [-100, 0, 0], 'hip-right': [-100, 0, 0], 'lumbar-spine': [12, 0, 0] }], { alias: 'Halasana', note: 'The starting inversion, neck support, and foot-to-floor contact are not simulated.' });
y('three-limbed-fold', 'Three-limbed seated fold', 'hips', 'Long sitting', 'One knee folds back while the trunk inclines over the other extended leg.', [{ 'hip-right': [-55, 0, 8], 'femur-right': [145, 0, 0] }, { pelvis: [20, 0, 0], 'hip-left': [-110, 0, 0], 'hip-right': [-75, 0, 8], 'femur-right': [145, 0, 0], 'lumbar-spine': [8, 0, 0], ...forwardArms }], { alias: 'Trianga Mukhaikapada Paschimottanasana' });
y('revolved-head-knee', 'Revolved head-to-knee arrangement', 'spine', 'Long sitting', 'A bent leg and long leg form the base for a lateral trunk arc and overhead reach.', [{ 'hip-left': [-90, -25, 0], ...foldedLeg('right', [1, 0, .7], [-1, 0, -.3]) }, { 'hip-left': [-90, -25, 0], ...foldedLeg('right', [1, 0, .7], [-1, 0, -.3]), 'lumbar-spine': [0, 8, 18], 'thoracic-lower': [0, 10, 12], 'scapula-right': [0, 0, 80] }], { alias: 'Parivrtta Janu Sirsasana' });
y('side-plank', 'Side plank arrangement', 'whole', 'Side lying', 'A long side-facing trunk and legs align above one extended arm as the other arm opens.', [{ 'scapula-left': [0, 0, 0], 'scapula-right': [0, 0, -45] }, { 'scapula-left': [0, 0, 0], 'scapula-right': [0, 0, 0], 'hip-right': [0, 0, 5] }], { base: { ...armsDown, root: [0, 0, 90] }, placement: { root: [900, 600, 0] }, alias: 'Vasisthasana Vasistasana', note: 'Hand and foot support are approximate; balance is not simulated.' });

a('constructive-rest', 'Constructive rest', 'spine', 'Supine', 'A bent-knee resting reference allows the arms and upper trunk to settle slightly.', [{ 'scapula-left': [0, 0, 80], 'scapula-right': [0, 0, -80] }, { 'scapula-left': [0, 0, 75], 'scapula-right': [0, 0, -75], 'thoracic-upper': [-2, 0, 0] }], { group: 'Resting and sitting' });
a('sitting-at-ease', 'Sitting at ease', 'spine', 'Seated', 'Small pelvic and spinal changes illustrate settling into an upright seated relationship.', [{ pelvis: [3, 0, 0], 'lumbar-spine': [-3, 0, 0] }, { pelvis: [-2, 0, 0], 'lumbar-spine': [2, 0, 0], 'thoracic-upper': [-2, 0, 0] }], { group: 'Resting and sitting' });
a('seated-conversation-turn', 'Turning toward someone while seated', 'head', 'Seated', 'The head turns before the chest joins the orientation toward a person beside the chair.', [{ head: [0, 15, 0] }, { head: [0, 8, 0], 'thoracic-upper': [0, 8, 0], 'thoracic-lower': [0, 5, 0] }], { group: 'Resting and sitting' });
a('chair-forward-shift', 'Moving forward on a chair', 'hips', 'Seated', 'A small torso incline precedes a short forward shift of the seated pelvis.', [{ 'lumbar-spine': [3, 0, 0], 'thoracic-lower': [3, 0, 0] }, { 'hip-left': [-85, 0, 0], 'hip-right': [-85, 0, 0], 'femur-left': [85, 0, 0], 'femur-right': [85, 0, 0] }], { group: 'Resting and sitting', translations: [{}, { root: [0, 0, 35] }] });
a('returning-to-chair', 'Returning to sitting', 'whole', 'Standing', 'Hips and knees fold together as the trunk inclines toward a seated arrangement.', [{ 'hip-left': [-25, 0, 0], 'hip-right': [-25, 0, 0], 'femur-left': [45, 0, 0], 'femur-right': [45, 0, 0] }, { 'hip-left': [-65, 0, 0], 'hip-right': [-65, 0, 0], 'femur-left': [95, 0, 0], 'femur-right': [95, 0, 0], 'thoracic-lower': [6, 0, 0] }], { group: 'Standing and walking', planted: true });
a('first-step', 'Taking the first step', 'legs', 'Standing', 'A pause precedes one hip and knee beginning a forward step.', [{ 'hip-left': [-12, 0, 0], 'femur-left': [22, 0, 0] }, { 'hip-left': [-24, 0, 0], 'femur-left': [18, 0, 0], 'tibia-left': [6, 0, 0], 'scapula-right': [0, -10, -90] }], { group: 'Standing and walking' });
a('walking-turn', 'Walking and turning', 'whole', 'Standing', 'Alternating leg shapes accompany a small change in whole-body direction.', [{ 'hip-left': [-18, 0, 0], 'hip-right': [12, 0, 0], 'femur-left': [25, 0, 0] }, { root: [0, 25, 0], 'hip-right': [-18, 0, 0], 'hip-left': [12, 0, 0], 'femur-right': [25, 0, 0] }], { group: 'Standing and walking', note: 'A schematic gait fragment; stride contacts are not solved.' });
a('hip-bending', 'Bending at the hips', 'hips', 'Standing', 'The trunk inclines through a hip hinge while the knees soften and the neck stays aligned.', [{ pelvis: [18, 0, 0], 'hip-left': [-25, 0, 0], 'hip-right': [-25, 0, 0], 'femur-left': [14, 0, 0], 'femur-right': [14, 0, 0] }, { pelvis: [32, 0, 0], 'hip-left': [-44, 0, 0], 'hip-right': [-44, 0, 0], 'femur-left': [24, 0, 0], 'femur-right': [24, 0, 0] }], { group: 'Bending and reaching', planted: true });
a('shelf-reach', 'Reaching toward a shelf', 'shoulders', 'Standing', 'One arm rises toward a shelf with a small accompanying upper-trunk change.', [{ 'scapula-left': [0, 65, 30], 'humerus-left': [0, 25, 0] }, { 'scapula-left': [0, 70, -25], 'humerus-left': [0, 8, 0], 'thoracic-upper': [-2, 0, 0] }], { group: 'Bending and reaching' });
a('floor-reach', 'Reaching toward the floor', 'whole', 'Standing', 'Hip and knee flexion bring a reaching hand lower while the trunk inclines.', [{ pelvis: [20, 0, 0], 'hip-left': [-45, 0, 0], 'hip-right': [-45, 0, 0], 'femur-left': [50, 0, 0], 'femur-right': [50, 0, 0] }, { pelvis: [35, 0, 0], 'hip-left': [-65, 0, 0], 'hip-right': [-65, 0, 0], 'femur-left': [60, 0, 0], 'femur-right': [60, 0, 0], 'scapula-left': [0, 20, 90] }], { group: 'Bending and reaching', planted: true });
a('door-opening', 'Opening a door', 'shoulders', 'Standing', 'An arm reaches forward, folds back, and accompanies a small trunk turn.', [{ 'scapula-left': [0, 65, 90], 'humerus-left': [0, 15, 0] }, { 'scapula-left': [0, 30, 90], 'humerus-left': [0, 75, 0], 'thoracic-upper': [0, 8, 0] }], { group: 'Bending and reaching' });
a('light-object-lift', 'Lifting a light object', 'whole', 'Standing', 'Bent hips and knees lengthen as two arms bring an imagined object nearer the trunk.', [{ 'hip-left': [-30, 0, 0], 'hip-right': [-30, 0, 0], 'femur-left': [50, 0, 0], 'femur-right': [50, 0, 0], ...forwardArms }, { 'hip-left': [-5, 0, 0], 'hip-right': [-5, 0, 0], 'femur-left': [10, 0, 0], 'femur-right': [10, 0, 0], ...bentArms }], { group: 'Lifting and carrying', planted: true });
a('carrying-bag', 'Carrying a bag', 'whole', 'Standing', 'A small arm fold accompanies alternating leg motion beside an upright trunk.', [{ 'humerus-left': [0, 20, 0], 'hip-right': [-15, 0, 0], 'femur-right': [22, 0, 0] }, { 'humerus-left': [0, 20, 0], 'hip-left': [-15, 0, 0], 'femur-left': [22, 0, 0], 'scapula-right': [0, -10, -90] }], { group: 'Lifting and carrying', note: 'The bag, its mass, and load compensation are not simulated.' });
a('object-setting-down', 'Setting an object down', 'hips', 'Standing', 'A forward arm reach precedes a small hip hinge toward a surface.', [bentArms, { ...forwardArms, pelvis: [18, 0, 0], 'hip-left': [-25, 0, 0], 'hip-right': [-25, 0, 0], 'femur-left': [14, 0, 0], 'femur-right': [14, 0, 0] }], { group: 'Lifting and carrying', planted: true });
a('stair-step', 'Stepping onto a stair', 'legs', 'Standing', 'One hip and knee lift toward an imagined step and then partly extend.', [{ 'hip-left': [-40, 0, 0], 'femur-left': [70, 0, 0], 'tibia-left': [-30, 0, 0] }, { 'hip-left': [-25, 0, 0], 'femur-left': [35, 0, 0], 'tibia-left': [-10, 0, 0], 'hip-right': [8, 0, 0] }], { group: 'Lifting and carrying', translations: [{}, { root: [0, 100, 35] }], note: 'Stair contact and balance are not simulated.' });
a('keyboard-approach', 'Hands moving to a keyboard', 'shoulders', 'Seated', 'Both forearms approach a desk-height relationship while the upper arms remain close to the trunk.', [{ 'humerus-left': [0, 55, 0], 'humerus-right': [0, -55, 0] }, { 'scapula-left': [0, 15, 90], 'scapula-right': [0, -15, -90], 'humerus-left': [0, 80, 0], 'humerus-right': [0, -80, 0] }], { group: 'Desk and everyday activities' });
a('mouse-use', 'Using a mouse', 'shoulders', 'Seated', 'A supported forearm makes a small sideways reach with a modest wrist adjustment.', [{ 'scapula-right': [0, -8, -82], 'forearm-right': [0, 5, 0] }, { 'scapula-right': [0, -8, -74], 'forearm-right': [0, -5, 0] }], { base: { ...seated, 'humerus-right': [0, -80, 0] }, group: 'Desk and everyday activities' });
a('cup-raising', 'Raising a cup', 'shoulders', 'Seated', 'The elbow folds as one hand approaches the face, with a small shoulder contribution.', [{ 'scapula-right': [0, -20, -75], 'humerus-right': [0, -80, 0] }, { 'scapula-right': [0, -40, -65], 'humerus-right': [0, -125, 0], 'forearm-right': [0, 0, 5] }], { group: 'Desk and everyday activities', note: 'The cup and precise hand-to-mouth contact are not rendered.' });
a('screen-turn', 'Turning toward a screen', 'head', 'Seated', 'A small head turn is followed by a coordinated upper-trunk turn toward a screen.', [{ head: [0, -12, 0] }, { head: [0, -6, 0], 'neck-base': [0, -5, 0], 'thoracic-upper': [0, -8, 0] }], { group: 'Desk and everyday activities' });

const expected = { feldenkrais: 39, yoga: 39, alexander: 19 };
for (const [tradition, count] of Object.entries(expected)) {
  if (studies.filter(study => study.tradition === tradition).length !== count) throw new Error(`Wrong expansion count for ${tradition}`);
}
export const expandedStudies = studies;
