#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/gh-pages"

# Get version info from environment or defaults
BRANCH_NAME="${BRANCH_NAME:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')}"
PR_NUMBER="${PR_NUMBER:-}"
VERSION_NAME="${VERSION_NAME:-$BRANCH_NAME}"

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Copy source assets and decks
cp -r "$ROOT_DIR/decks" "$OUTPUT_DIR/decks"
cp "$ROOT_DIR/manifest.webmanifest" "$OUTPUT_DIR/manifest.webmanifest"

# Generate cache version and inject into service worker
CACHE_VERSION="v$(date +%s)"
sed "s/__CACHE_VERSION__/$CACHE_VERSION/g" "$ROOT_DIR/sw.js" > "$OUTPUT_DIR/sw.js"
if [ -d "$ROOT_DIR/pwa" ]; then
  cp -r "$ROOT_DIR/pwa" "$OUTPUT_DIR/pwa"
fi

# Generate a simple root index linking all decks
mapfile -t DECKS < <(find "$ROOT_DIR/decks" -maxdepth 1 -mindepth 1 -type d -print | sort | while read -r path; do basename "$path"; done)

if [ "${#DECKS[@]}" -eq 0 ]; then
  echo "No decks found in $ROOT_DIR/decks"
  exit 1
fi

DEFAULT_STYLE="./decks/${DECKS[0]}/assets/styles.css"
DEFAULT_SCRIPT="./decks/${DECKS[0]}/assets/scripts.js"

cat > "$OUTPUT_DIR/index.html" <<EOF_HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SitePrep Decks</title>
  <link rel="stylesheet" href="$DEFAULT_STYLE">
  <link rel="manifest" href="./manifest.webmanifest">
  <script defer src="$DEFAULT_SCRIPT"></script>
</head>
<body>
  <header class="card">
    <div class="card-header">
      <p class="tag">Root Index</p>
      <h1>SitePrep Decks</h1>
    </div>
    <div class="card-content">
      <p>Browse available decks generated by the SitePrep experiment. Content is organized by deck, section, and individual pages.</p>
      <p style="margin-top: 1rem;"><a href="./index-versions.html">View all versions (including PR previews)</a></p>
    </div>
  </header>
  <main class="card" aria-labelledby="deck-list-title">
    <div class="card-header">
      <h2 id="deck-list-title">Decks</h2>
      <p class="meta">Current catalog of published decks.</p>
    </div>
    <div class="card-content">
      <ul class="toc-grid">
EOF_HTML

for deck in "${DECKS[@]}"; do
  cat >> "$OUTPUT_DIR/index.html" <<EOF_HTML
        <li class="toc-item">
          <h3>${deck}</h3>
          <p>Generated from source in decks/${deck}/</p>
          <a href="./decks/${deck}/index.html">Open deck</a>
        </li>
EOF_HTML
done

cat >> "$OUTPUT_DIR/index.html" <<'EOF_HTML'
      </ul>
    </div>
  </main>
</body>
</html>
EOF_HTML

# Function to inject version footer into HTML files
inject_version_footer() {
  local html_file="$1"

  # Determine the base path for the site
  local repo_name=$(basename "$(git rev-parse --show-toplevel 2>/dev/null || echo 'siteprep')")

  # Create footer HTML
  local footer_html="  <footer style=\"text-align: center; padding: 2rem 1rem; margin-top: 2rem; border-top: 1px solid #e0e0e0; color: #666; font-size: 0.9rem;\">"
  footer_html="$footer_html<p>Version: <strong>$VERSION_NAME</strong>"
  if [ -n "$PR_NUMBER" ]; then
    footer_html="$footer_html (Branch: $BRANCH_NAME)"
  fi
  footer_html="$footer_html</p>"
  footer_html="$footer_html<p><a href=\"/$repo_name/index-versions.html\" style=\"color: #0066cc;\">View all versions</a></p>"
  footer_html="$footer_html</footer>"

  # Insert footer before closing body tag
  if grep -q "</body>" "$html_file"; then
    # Use a temporary file to avoid in-place editing issues
    local tmp_file="${html_file}.tmp"
    awk -v footer="$footer_html" '
      /<\/body>/ {
        print footer
      }
      { print }
    ' "$html_file" > "$tmp_file"
    mv "$tmp_file" "$html_file"
  fi
}

# Inject version info into all HTML files
echo "Injecting version info into HTML files..."
while IFS= read -r -d '' html_file; do
  inject_version_footer "$html_file"
done < <(find "$OUTPUT_DIR" -name "*.html" -type f -print0)

"$ROOT_DIR/scripts/build_tests.sh"

printf 'Build complete. Output stored in %s\n' "$OUTPUT_DIR"
printf 'Version: %s (Branch: %s)\n' "$VERSION_NAME" "$BRANCH_NAME"
