#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/gh-pages"

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Copy source assets and decks
cp -r "$ROOT_DIR/decks" "$OUTPUT_DIR/decks"
cp "$ROOT_DIR/manifest.webmanifest" "$OUTPUT_DIR/manifest.webmanifest"
cp "$ROOT_DIR/sw.js" "$OUTPUT_DIR/sw.js"
if [ -d "$ROOT_DIR/pwa" ]; then
  cp -r "$ROOT_DIR/pwa" "$OUTPUT_DIR/pwa"
fi

# Generate a simple root index linking all decks
mapfile -t DECKS < <(find "$ROOT_DIR/decks" -maxdepth 1 -mindepth 1 -type d -print | sort | while read -r path; do basename "$path"; done)

if [ "${#DECKS[@]}" -eq 0 ]; then
  echo "No decks found in $ROOT_DIR/decks"
  exit 1
fi

DEFAULT_STYLE="./decks/${DECKS[0]}/assets/styles.css"
DEFAULT_SCRIPT="./decks/${DECKS[0]}/assets/scripts.js"

cat > "$OUTPUT_DIR/index.html" <<EOF_HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SitePrep Decks</title>
  <link rel="stylesheet" href="$DEFAULT_STYLE">
  <link rel="manifest" href="./manifest.webmanifest">
  <script defer src="$DEFAULT_SCRIPT"></script>
</head>
<body>
  <header class="card">
    <div class="card-header">
      <p class="tag">Root Index</p>
      <h1>SitePrep Decks</h1>
    </div>
    <div class="card-content">
      <p>Browse available decks generated by the SitePrep experiment. Content is organized by deck, section, and individual pages.</p>
    </div>
  </header>
  <main class="card" aria-labelledby="deck-list-title">
    <div class="card-header">
      <h2 id="deck-list-title">Decks</h2>
      <p class="meta">Current catalog of published decks.</p>
    </div>
    <div class="card-content">
      <ul class="toc-grid">
EOF_HTML

for deck in "${DECKS[@]}"; do
  cat >> "$OUTPUT_DIR/index.html" <<EOF_HTML
        <li class="toc-item">
          <h3>${deck}</h3>
          <p>Generated from source in decks/${deck}/</p>
          <a href="./decks/${deck}/index.html">Open deck</a>
        </li>
EOF_HTML
done

cat >> "$OUTPUT_DIR/index.html" <<'EOF_HTML'
      </ul>
    </div>
  </main>
</body>
</html>
EOF_HTML

if [ -x "$ROOT_DIR/scripts/build_tests.sh" ]; then
  "$ROOT_DIR/scripts/build_tests.sh" "$OUTPUT_DIR" "$ROOT_DIR"
fi

printf 'Build complete. Output stored in %s\n' "$OUTPUT_DIR"
