#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/gh-pages"

# Get version info from environment or defaults
BRANCH_NAME="${BRANCH_NAME:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')}"
PR_NUMBER="${PR_NUMBER:-}"
VERSION_NAME="${VERSION_NAME:-$BRANCH_NAME}"

# Function to read deck metadata from deck.json
get_deck_metadata() {
  local deck_dir="$1"
  local deck_name="$2"
  local field="$3"

  local json_file="$deck_dir/deck.json"

  # If deck.json doesn't exist, return deck name as default
  if [ ! -f "$json_file" ]; then
    echo "$deck_name"
    return
  fi

  # Try to extract field from JSON using grep/sed (avoiding jq dependency)
  local value=$(grep -o "\"$field\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$json_file" 2>/dev/null | sed 's/.*:.*"\(.*\)".*/\1/')

  # If field not found or empty, return deck name as default
  if [ -z "$value" ]; then
    echo "$deck_name"
  else
    echo "$value"
  fi
}

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Copy source assets and decks
cp -r "$ROOT_DIR/decks" "$OUTPUT_DIR/decks"
cp -r "$ROOT_DIR/shared_assets" "$OUTPUT_DIR/shared_assets"
cp "$ROOT_DIR/manifest.webmanifest" "$OUTPUT_DIR/manifest.webmanifest"

# Generate cache version and inject into service worker
CACHE_VERSION="v$(date +%s)"
sed "s/__CACHE_VERSION__/$CACHE_VERSION/g" "$ROOT_DIR/sw.js" > "$OUTPUT_DIR/sw.js"
if [ -d "$ROOT_DIR/pwa" ]; then
  cp -r "$ROOT_DIR/pwa" "$OUTPUT_DIR/pwa"
fi

# Discover decks and build metadata arrays
declare -A DECK_TITLES
declare -A DECK_SORT_ORDERS
declare -A DECK_DESCRIPTIONS

mapfile -t DECK_NAMES < <(find "$ROOT_DIR/decks" -maxdepth 1 -mindepth 1 -type d -print | while read -r path; do basename "$path"; done)

if [ "${#DECK_NAMES[@]}" -eq 0 ]; then
  echo "No decks found in $ROOT_DIR/decks"
  exit 1
fi

# Read metadata for each deck
for deck_name in "${DECK_NAMES[@]}"; do
  deck_dir="$ROOT_DIR/decks/$deck_name"
  DECK_TITLES[$deck_name]=$(get_deck_metadata "$deck_dir" "$deck_name" "title")
  DECK_SORT_ORDERS[$deck_name]=$(get_deck_metadata "$deck_dir" "$deck_name" "sort_order")
  DECK_DESCRIPTIONS[$deck_name]=$(get_deck_metadata "$deck_dir" "$deck_name" "description")
done

# Sort decks by sort_order
mapfile -t SORTED_DECKS < <(
  for deck_name in "${DECK_NAMES[@]}"; do
    echo "${DECK_SORT_ORDERS[$deck_name]}|$deck_name"
  done | sort | cut -d'|' -f2
)

# Use first sorted deck for default styles
DEFAULT_STYLE="./decks/${SORTED_DECKS[0]}/assets/styles.css"
DEFAULT_SCRIPT="./decks/${SORTED_DECKS[0]}/assets/scripts.js"

cat > "$OUTPUT_DIR/index.html" <<EOF_HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SitePrep Decks</title>
  <link rel="icon" href="./shared_assets/favicon.png" type="image/png">
  <link rel="stylesheet" href="$DEFAULT_STYLE">
  <link rel="manifest" href="./manifest.webmanifest">
  <script defer src="$DEFAULT_SCRIPT"></script>
</head>
<body>
  <header class="card">
    <div class="card-header">
      <p class="tag">Root Index</p>
      <h1>SitePrep Decks</h1>
    </div>
    <div class="card-content">
      <p>Browse available decks generated by the SitePrep experiment. Content is organized by deck, section, and individual pages.</p>
      <p style="margin-top: 1rem;"><a href="./index-versions.html">View all versions (including PR previews)</a></p>
    </div>
  </header>
  <main class="card" aria-labelledby="deck-list-title">
    <div class="card-header">
      <h2 id="deck-list-title">Decks</h2>
      <p class="meta">Current catalog of published decks.</p>
    </div>
    <div class="card-content">
      <ul class="toc-grid">
EOF_HTML

for deck in "${SORTED_DECKS[@]}"; do
  title="${DECK_TITLES[$deck]}"
  description="${DECK_DESCRIPTIONS[$deck]}"

  cat >> "$OUTPUT_DIR/index.html" <<EOF_HTML
        <li class="toc-item">
          <a href="./decks/${deck}/index.html" class="toc-link">
            <h3>${title}</h3>
            <p>${description}</p>
          </a>
        </li>
EOF_HTML
done

cat >> "$OUTPUT_DIR/index.html" <<'EOF_HTML'
      </ul>
    </div>
  </main>
</body>
</html>
EOF_HTML

# Create a placeholder index-versions.html (will be replaced during deployment)
cat > "$OUTPUT_DIR/index-versions.html" <<EOF_VERSIONS
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SitePrep - All Versions</title>
  <link rel="stylesheet" href="$DEFAULT_STYLE">
</head>
<body>
  <header class="card">
    <div class="card-header">
      <a href="index-versions.html" class="tag">Version Browser</a>
      <h1>SitePrep - All Versions</h1>
    </div>
    <div class="card-content">
      <p>This page lists all available versions including PR previews.</p>
      <p>The full versions index is generated during deployment to GitHub Pages.</p>
      <p><a href="./index.html">Return to main index</a></p>
    </div>
  </header>
</body>
</html>
EOF_VERSIONS

# Function to inject version footer into HTML files
inject_version_footer() {
  local html_file="$1"

  # Calculate relative path from this HTML file to the root
  local rel_path=$(realpath --relative-to="$(dirname "$html_file")" "$OUTPUT_DIR")
  if [ "$rel_path" = "." ]; then
    rel_path=""
  else
    rel_path="$rel_path/"
  fi

  # Determine page context (root, deck, or section)
  local file_rel_path="${html_file#$OUTPUT_DIR/}"
  local page_type="root"
  local deck_path=""
  local section_path=""

  if [[ "$file_rel_path" =~ ^decks/([^/]+)/sections/([^/]+)/ ]]; then
    page_type="section"
    deck_path="../../index.html"
    section_path="overview.html"
  elif [[ "$file_rel_path" =~ ^decks/([^/]+)/index\.html$ ]]; then
    page_type="deck"
    deck_path="index.html"
  fi

  # Create footer HTML with JavaScript for dynamic rendering
  local footer_html="  <footer class=\"site-footer\">\n"
  footer_html="${footer_html}    <script>\n"
  footer_html="${footer_html}      (function() {\n"
  footer_html="${footer_html}        var footer = document.currentScript.parentElement;\n"
  footer_html="${footer_html}        var nav = document.createElement('div');\n"
  footer_html="${footer_html}        nav.className = 'footer-nav';\n"
  footer_html="${footer_html}        var links = [];\n"
  footer_html="${footer_html}        \n"
  footer_html="${footer_html}        // Version link to home\n"
  footer_html="${footer_html}        links.push({ href: '${rel_path}index.html', text: 'Version: $VERSION_NAME' });\n"
  footer_html="${footer_html}        \n"

  # Add deck link if applicable
  if [ "$page_type" = "deck" ] || [ "$page_type" = "section" ]; then
    footer_html="${footer_html}        // Deck link\n"
    footer_html="${footer_html}        links.push({ href: '${deck_path}', text: 'Deck' });\n"
    footer_html="${footer_html}        \n"
  fi

  # Add section link if applicable
  if [ "$page_type" = "section" ]; then
    footer_html="${footer_html}        // Section link\n"
    footer_html="${footer_html}        links.push({ href: '${section_path}', text: 'Section' });\n"
    footer_html="${footer_html}        \n"
  fi

  # Add Google Drive and View all versions links
  footer_html="${footer_html}        // Google Drive link\n"
  footer_html="${footer_html}        links.push({ href: 'https://drive.google.com/drive/folders/1BDF-8Vz_8P5PIH_78GikTFfYA_ZtOoUS?usp=drive_link', text: 'Google Drive', external: true });\n"
  footer_html="${footer_html}        \n"
  footer_html="${footer_html}        // View all versions link\n"
  footer_html="${footer_html}        links.push({ href: '${rel_path}index-versions.html', text: 'View all versions' });\n"
  footer_html="${footer_html}        \n"
  footer_html="${footer_html}        // Build the navigation\n"
  footer_html="${footer_html}        links.forEach(function(link, index) {\n"
  footer_html="${footer_html}          if (index > 0) {\n"
  footer_html="${footer_html}            var sep = document.createElement('span');\n"
  footer_html="${footer_html}            sep.className = 'footer-separator';\n"
  footer_html="${footer_html}            sep.textContent = '|';\n"
  footer_html="${footer_html}            nav.appendChild(sep);\n"
  footer_html="${footer_html}          }\n"
  footer_html="${footer_html}          var a = document.createElement('a');\n"
  footer_html="${footer_html}          a.href = link.href;\n"
  footer_html="${footer_html}          a.textContent = link.text;\n"
  footer_html="${footer_html}          if (link.external) a.target = '_blank';\n"
  footer_html="${footer_html}          nav.appendChild(a);\n"
  footer_html="${footer_html}        });\n"
  footer_html="${footer_html}        \n"
  footer_html="${footer_html}        footer.appendChild(nav);\n"
  footer_html="${footer_html}      })();\n"
  footer_html="${footer_html}    </script>\n"
  footer_html="${footer_html}  </footer>"

  # Insert footer before closing body tag
  if grep -q "</body>" "$html_file"; then
    # Use a temporary file to avoid in-place editing issues
    local tmp_file="${html_file}.tmp"
    awk -v footer="$footer_html" '
      /<\/body>/ {
        print footer
      }
      { print }
    ' "$html_file" > "$tmp_file"
    mv "$tmp_file" "$html_file"
  fi
}

# Inject version info into all HTML files
echo "Injecting version info into HTML files..."
while IFS= read -r -d '' html_file; do
  inject_version_footer "$html_file"
done < <(find "$OUTPUT_DIR" -name "*.html" -type f -print0)

"$ROOT_DIR/scripts/build_tests.sh"

printf 'Build complete. Output stored in %s\n' "$OUTPUT_DIR"
printf 'Version: %s (Branch: %s)\n' "$VERSION_NAME" "$BRANCH_NAME"
