#!/usr/bin/env node
// Generate the Skills index in README.md from the skills themselves.
//
//   node scripts/skills_index.mjs           rewrite the index in place
//   node scripts/skills_index.mjs --check   fail if the index is out of date
//
// The index is written between the BEGIN/END markers in README.md. Every skill
// discoverable in this repository lives in one immediate subdirectory of
// .claude/skills/, so the index is the frontmatter of .claude/skills/*/SKILL.md
// and nothing else. Hand-editing the marked block is pointless: the next run of
// this script overwrites it, and --check fails the build in the meantime.

import {readFileSync, readdirSync, writeFileSync, existsSync} from 'node:fs';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(REPO_ROOT, '.claude', 'skills');
const README = join(REPO_ROOT, 'README.md');
const BEGIN = '<!-- BEGIN GENERATED SKILLS INDEX -->';
const END = '<!-- END GENERATED SKILLS INDEX -->';

// Read the `name` and `description` of a SKILL.md frontmatter block. Values may
// continue onto following indented lines, which is how a long description is
// wrapped; they are joined back into one line.
function readFrontmatter(path) {
  const lines = readFileSync(path, 'utf8').split('\n');
  if (lines[0].trim() !== '---') {
    throw new Error(`${path}: no frontmatter`);
  }
  const end = lines.indexOf('---', 1);
  if (end === -1) {
    throw new Error(`${path}: unterminated frontmatter`);
  }

  const fields = {};
  let key = null;
  for (const line of lines.slice(1, end)) {
    const match = /^([A-Za-z_][\w-]*):\s*(.*)$/.exec(line);
    if (match) {
      key = match[1];
      fields[key] = match[2].trim();
    } else if (key && line.trim()) {
      fields[key] += ` ${line.trim()}`;
    }
  }
  for (const required of ['name', 'description']) {
    if (!fields[required]) {
      throw new Error(`${path}: frontmatter has no ${required}`);
    }
  }
  return fields;
}

// The description is written to make the skill trigger, so it opens with what
// the skill does and then goes on to when to use it. The index wants the first
// part. Split only at a sentence end followed by a capital, so that a filename
// like decisions.md does not read as one.
function summarize(description) {
  const [first] = description.split(/(?<=\.)\s+(?=[A-Z])/);
  return first.replace(/\s+/g, ' ').trim();
}

function collectSkills() {
  if (!existsSync(SKILLS_DIR)) {
    throw new Error(`${SKILLS_DIR} does not exist`);
  }
  const skills = [];
  for (const entry of readdirSync(SKILLS_DIR, {withFileTypes: true})) {
    // A symlinked skill directory is a second discovery path for a skill that
    // is already listed under its real name, so follow directories only.
    if (!entry.isDirectory()) continue;
    const skillFile = join(SKILLS_DIR, entry.name, 'SKILL.md');
    if (!existsSync(skillFile)) {
      throw new Error(`.claude/skills/${entry.name}/ has no SKILL.md`);
    }
    const {name, description} = readFrontmatter(skillFile);
    if (name !== entry.name) {
      throw new Error(
        `.claude/skills/${entry.name}/SKILL.md declares name "${name}"; ` +
          'the frontmatter name and the directory name must match',
      );
    }
    skills.push({name, summary: summarize(description)});
  }
  if (skills.length === 0) {
    throw new Error(`${SKILLS_DIR} contains no skills`);
  }
  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

function renderIndex(skills) {
  const lines = skills.map(
    ({name, summary}) =>
      `- [\`${name}\`](.claude/skills/${name}/SKILL.md) — ${summary}`,
  );
  return [
    BEGIN,
    '<!-- Generated by scripts/skills_index.mjs. Do not edit by hand. -->',
    '',
    ...lines,
    '',
    END,
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const readme = readFileSync(README, 'utf8');
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (begin === -1 || end === -1 || end < begin) {
    console.error(`README.md is missing the ${BEGIN} / ${END} markers`);
    process.exit(1);
  }

  const generated = renderIndex(collectSkills());
  const updated = readme.slice(0, begin) + generated + readme.slice(end + END.length);

  if (updated === readme) {
    console.log(`Skills index is up to date (${collectSkills().length} skills).`);
    return;
  }
  if (check) {
    console.error(
      'README.md skills index is out of date. Run: node scripts/skills_index.mjs',
    );
    process.exit(1);
  }
  writeFileSync(README, updated);
  console.log(`Wrote skills index to README.md (${collectSkills().length} skills).`);
}

try {
  main();
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
